workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 60
    environment:
      java: 17
      vars:
        KEYSTORE_PATH: keystore.jks
        KEYSTORE_PASSWORD: $KEYSTORE_PASSWORD
        KEY_ALIAS: $KEY_ALIAS
        KEY_PASSWORD: $KEY_PASSWORD
    scripts:
      - name: Build APK
        script: |
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
