
workflows:
  android-workflow:
    name: Android Build Workflow
    max_build_duration: 30
    environment:
      android_signing:
        - keystore_reference
      vars:
        JAVA_VERSION: 17
    triggering:
      events:
        - push
    scripts:
      - name: Set up Java
        script: |
          sdkmanager --install "cmdline-tools;latest"
          sdkmanager --install "build-tools;34.0.0"
          sdkmanager --install "platforms;android-34"
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - build/outputs/**/*.apk
