workflows:
  android-build:
    name: Android Build
    environment:
      android:
        sdk: 34  # تحديد إصدار Android SDK المطلوب
      java: 17   # تحديد إصدار Java
    scripts:
      - name: تثبيت Android SDK
        script: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-mac-9477386_latest.zip
          unzip sdk-tools.zip -d latest
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      - name: بناء التطبيق
        script: ./gradlew assembleDebug
    artifacts:
      - build/outputs/**/*.apk
