workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
      android_signing:
        keystore_path: keystore.keystore
        keystore_password: $KEYSTORE_PASSWORD
        key_alias: $KEY_ALIAS
        key_password: $KEY_PASSWORD
    scripts:
      - name: Build APK
        script: |
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
